---
- name: MyEc2
  hosts: all
  become: = yes
  tasks:
    - name: Systen-Udate
      yum:
        update_cache: yes

      
- name: HTOP instalieren
  yum:
    name: HTOP
    state: present 


- name: Update repositories cach and install "foo" package
  apt:
    name: "foo"
    update_cache: yes
